# Generated by Django 5.0.2 on 2024-05-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_prompt_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_development', models.TextField(blank=True, null=True)),
                ('meeting_attended', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialmediasection',
            name='keywords',
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediasection',
            name='category',
            field=models.ManyToManyField(blank=True, to='authentication.category'),
        ),
        migrations.RemoveField(
            model_name='companylist',
            name='category',
        ),
        migrations.CreateModel(
            name='SocialMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_file', models.FileField(upload_to='case_studies_files/')),
                ('social_media_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentication.socialmediasection')),
            ],
        ),
        migrations.AddField(
            model_name='companylist',
            name='category',
            field=models.ManyToManyField(blank=True, to='authentication.category'),
        ),
    ]
