# Generated by Django 5.0.2 on 2024-05-29 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_voucher_user_voucher_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voucher', to=settings.AUTH_USER_MODEL),
        ),
    ]
