# Generated by Django 5.0.2 on 2024-05-29 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_voucher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voucher', to=settings.AUTH_USER_MODEL)),
                ('voucher_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_user', to='authentication.voucher')),
            ],
        ),
    ]
