# Generated by Django 5.0.2 on 2024-03-06 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('channel', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_needed', models.BooleanField(blank=True, default=False, null=True)),
                ('image_needed_prompt', models.CharField(blank=True, max_length=100, null=True)),
                ('post_status', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Inprogress', 'Inprogress')], default='Inprogress', max_length=10, null=True)),
                ('generated_fb_post', models.TextField(blank=True, null=True)),
                ('generated_insta_post', models.TextField(blank=True, null=True)),
                ('generated_linkedin_post', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
