# Generated by Django 5.0.2 on 2024-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0003_generatepost_generated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepost',
            name='generated_image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
