# Generated by Django 5.0.2 on 2024-03-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0004_alter_generatepost_generated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepost',
            name='post_status',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Inprogress', 'Inprogress'), ('Live', 'Live')], default='Inprogress', max_length=10, null=True),
        ),
    ]
