# Generated by Django 5.0.2 on 2024-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0005_alter_generatepost_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='post_page_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
