# Generated by Django 5.0.2 on 2024-03-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0007_rename_post_page_post_id_generatepost_facebook_page_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='linkedin_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
