# Generated by Django 5.0.2 on 2024-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0010_generatepost_fb_page_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='Instagram_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatepost',
            name='Instagram_page_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
