# Generated by Django 5.0.2 on 2024-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0012_generatepost_instagram_page_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='linkedin_page_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
