# Generated by Django 5.0.2 on 2024-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0013_generatepost_linkedin_page_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='linkedin_page_image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
