# Generated by Django 5.0.2 on 2024-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0014_generatepost_linkedin_page_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='fb_page_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
