"""
Django settings for face project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!9-vntp@pqv9p&x$pc7+t5^6t4x9v&fc-)b3p(x7ffancwlj5%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'faces.ddivesocial.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'social_media_post',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'face.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'face.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# faces
BASE_URL = 'http://13.51.138.208:8000'


SOCIAL_AUTH_FACEBOOK_KEY = "1771703993310026"
SOCIAL_AUTH_FACEBOOK_SECRET = "ea6e4300df0e6087d9d6df63ac12bd84"



AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'https://facebook.com/'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'login'

'''
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '77jxi0297t51d6'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'cyGaBhJv2wh2LKpS'
'''
BASE_URL = "https://ddivesocial.com"
# BASE_URL = "http://51.20.176.13:8000"
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '775avibli3iksz'
# SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '78ul3zsyhxo85v'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'T9UilMukOzwU5Eup'
# SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'b4ABbFUWkEcabO2r'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE  = "w_member_social,email,profile,r_basicprofile,openid,w_organization_social,r_organization_social,r_organization_admin,rw_organization_admin"
LINKEDIN_REDIRECT_URL = f'{BASE_URL}/linkedin/callback/access/'
LINKEDIN_BASE_URL = "https://www.linkedin.com/oauth/v2/authorization"
LINKEDIN_ACCESS_URL = "https://www.linkedin.com/oauth/v2/accessToken"



# BASE_URL_FACEBOOK = 

#---------------AWS credentials----------#
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'ddive.ai'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_REGION_NAME = 'eu-north-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


#--------------------------celery-----------------------------#
# save Celery task results in Django's database
CELERY_RESULT_BACKEND = "django-db"


# user_info_url = f'https://graph.facebook.com/v12.0/me?fields=id,name,email&access_token={access_token}'
# user_info_response = requests.get(user_info_url)
# user_info = user_info_response.json()

# email = user_info.get('email')
# name = user_info.get('name')
# facebook_id = user_info.get('id')